apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demoapp01
resources:
  - app-deployment.yaml
  - service.yaml
  - namespace.yaml

commonLabels:
  owner: tradingaps
  app: demoapp01
