# Benyttets til at simulere cloud-loadbalancer & ingress eksempel
# Denne benyttes af ingress-nginx controller svc
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: public
  namespace: metallb-system
spec:
  addresses:
  - 10.255.0.245/32

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2advertisementingress
  namespace: metallb-system
spec:
  ipAddressPools:
  -  public
  nodeSelectors:
  - matchLabels: 
      app.kubernetes.io/component: controller
