apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging-website
bases:
  - ../base
namePrefix: staging-
resources:
  - service-loadbalancer.yaml
patches:
  - increase_hpa_count.yaml
