apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoapp01
  labels:
    app: demoapp01-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demoapp01
  template:
    metadata:
      labels:
        app: demoapp01
    spec:
      containers:
        - name: demoapp01
          image: thinnesen/application-tradingaps:79
