apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: website
    spec:
      resources:
        requests:
          memory: "26Mi"
          cpu: "25m"
        limits:
          memory: "500Mi"
          cpu: "2000m"