apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: website
spec:
  secretName: website
  issuerRef:
    name: acme-issuer
    kind: ClusterIssuer
  dnsNames:
  - 'website.tradingaps.com'