apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: website
spec:
  secretName: website
  duration: 4320h
  renewBefore: 240h
  issuerRef:
    name: acme-issuer
    kind: ClusterIssuer
  dnsNames:
  - 'tradingaps.com'