apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demoapp-production
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:Thinnesen/tradingaps-manifest.git
    targetRevision: HEAD
    path: manifests_demoapp01/production/
    directory:
      recurse: false
  destination:
    server: https://kubernetes.default.svc
    namespace: demoapp-production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true