apiVersion: v1
kind: Service
metadata:
  name: demoapp01-lb
  labels:
    app: demoapp01
spec:
  type: LoadBalancer
  ports:
  - name: demoapp01
    port: 3000
    targetPort: 3000
  selector:
    app: demoapp01