apiVersion: apps/v1
kind: Deployment
metadata:
  name: app01
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: app01
  template:
    metadata:
      labels:
        app: app01
    spec:
      containers:
        - name: app01
          image: thinnesen/trading_aps_staging:10
