apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging-app01
bases:
  - ../base
namePrefix: staging-
resources:
  - service-loadbalancer.yaml
patches:
  - app-deployment.yaml
