apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev-demoapp01
bases:
  - ../base
namePrefix: dev-
resources:
  - service-loadbalancer.yaml
patches:
  - increase_replicas.yaml