apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
  labels:
    app: website-deployment
spec:
#  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
        - name: website
          image: thinnesen/website-tradingaps:15
          resources:
            requests:
              memory: "15Mi"
              cpu: "27m"
            limits:
              memory: "600Mi"
              cpu: "2000m"
