apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: website
resources:
  - app-deployment.yaml
  - service.yaml
  - namespace.yaml
  - horizontalpodautoscaler.yaml

commonLabels:
  owner: tradingaps
  app: website
