apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: production-website
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:Thinnesen/tradingaps-manifest.git
    targetRevision: HEAD
    path: manifests_website/production/
    directory:
      recurse: false
  destination:
    server: https://kubernetes.default.svc
    namespace: production-website
  syncPolicy:
    automated:
      prune: true
      selfHeal: true