#indeholder cloudflare API-key
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-key-secret
  namespace: cert-manager
type: Opaque
stringData:
  api-key: 29d1ffaa655dd34fc61ea75742ac7775cbffb